name: nikhilv
favicon: null
layout_spectrum: 0.3269454501569271
typography_spectrum: 0.7968931253999472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.0213107168674469
  lightness: 0.2811296957079321
  saturation: 0.7424326208420098
  rhythmicContrast: 0.1198262854013592
purpose: []
